export const CAT_LIST_REQUEST='CAT_LIST_REQUEST';
export const CAT_LIST_SUCCESS='CAT_LIST_SUCCESS';
export const CAT_LIST_FAIL='CAT_LIST_FAIL';

export const AREA_LIST_REQUEST='AREA_LIST_REQUEST';
export const AREA_LIST_SUCCESS='AREA_LIST_SUCCESS';
export const AREA_LIST_FAIL='AREA_LIST_FAIL';

export const ING_LIST_REQUEST='ING_LIST_REQUEST';
export const ING_LIST_SUCCESS='ING_LIST_SUCCESS';
export const ING_LIST_FAIL='ING_LIST_FAIL';

export const SINGLE_CAT_REQUEST='SINGLE_CAT_REQUEST';
export const SINGLE_CAT_SUCCESS='SINGLE_CAT_SUCCESS';
export const SINGLE_CAT_FAIL='SINGLE_CAT_FAIL';

export const MEAL_DETAILS_REQUEST='MEAL_DETAILS_REQUEST';
export const MEAL_DETAILS_SUCCESS='MEAL_DETAILS_SUCCESS';
export const MEAL_DETAILS_FAIL='MEAL_DETAILS_FAIL';

export const SINGLE_AREA_REQUEST='SINGLE_AREA_REQUEST';
export const SINGLE_AREA_SUCCESS='SINGLE_AREA_SUCCESS';
export const SINGLE_AREA_FAIL='SINGLE_AREA_FAIL';